### ISSUE TITLE
Do not use for most 1.17+

### ISSUE THREAD

**Issue by SnowFlakeDif** [Draylar/angerable-patch#4]
This will cause errors and lower your TPS(Ticks per second) by a lot. I was getting 336ms which is like 3TPS and Minecraft normally tries to run at 20TPS. This will affect Mob movement and other tick updates. They will look very stuttery.

**Comment by Draylar** [comment]
Correct - this mod fixes a [1.16.5 bug that was patched in 1.17 snapshots](https://bugs.mojang.com/browse/MC-189565).
